In [1]:
from random import shuffle
import glob
import cv2
import matplotlib.pyplot as plt
import re
import numpy as np
%matplotlib inline

In [2]:
shuffle_data = True  # shuffle the addresses before saving
numpy_path = '/home/miguelmg/Documents/CIDETEC/semestre 2/vision 3d/proyecto/6d pose/hinterstoisser/nubes/dataset/11_ref_100.npy'  # address to where you want to save the numpy file
dataset_train_path = '/home/miguelmg/Documents/CIDETEC/semestre 2/vision 3d/proyecto/6d pose/hinterstoisser/nubes/dataset/11_ref/100/*.txt'

In [54]:
addrs = glob.glob(dataset_train_path)
labels = []
volumes = []
#extraer el primer numero del nombre del archivo, para guardar en un arreglo
i = 0
for file in addrs:
    m = re.search('11_ref/100/(.+?)_', file)
    #print (m.group(1))
    #print(file)
    labels.append(int(m.group(1)))
    array = np.loadtxt( file, dtype=float)
    volumes.append(array)
    if i % 100 == 0:
        print("Loading image: ", i)
    i = i + 1
    
print(len(labels), len(volumes))

Loading image:  0
6 6


In [49]:
c = list(zip(volumes, labels))
shuffle(c)
volumes, labels = zip(*c)
print(len(volumes), len(labels))

8 8


In [55]:
print((array))
np.save("11_ref_100_vol",volumes)

[0.228571 0.228571 0.228571 ... 0.228571 0.228571 0.228571]


In [56]:
np.save("11_ref_100_lbl", labels)

### Pruebas para cargar dataset

In [57]:
dataset_load_path = "/home/miguelmg/Documents/CIDETEC/semestre 2/vision 3d/proyecto/11_ref_100_vol.npy"
dataset_load_lbl_path = "/home/miguelmg/Documents/CIDETEC/semestre 2/vision 3d/proyecto/11_ref_100_lbl.npy"
dataset = np.load(dataset_load_path)
print(dataset.shape)

(6, 32768)


In [58]:
labels_ = np.load(dataset_load_lbl_path)
print((labels_.shape))
labels_ = np.array(labels_)
print(labels_)

(6,)
[ 0  8 11  9  5  1]


In [59]:
one_hot = np.zeros((len(labels_),14))
one_hot[np.arange(len(labels_)),labels_]=1
print(one_hot)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
a = np.array([1,2,3,5])
b = np.array([6,7,8,9])
print(a,b)
c = list(zip(a,b))
shuffle(c)
a,b = zip(*c)
print(a,b)

[1 2 3 5] [6 7 8 9]
(3, 2, 1, 5) (8, 7, 6, 9)
