In [1]:
import numpy as np
import glob
from scipy.spatial import distance
import re

In [25]:
input_file = np.genfromtxt('/home/miguelmg/Documents/CIDETEC/semestre 2/vision 3d/proyecto/6d pose/hinterstoisser/nubes/dataset/test_DNN/programas/equiv_class2pose.txt')
output_folder = '/home/miguelmg/Documents/CIDETEC/semestre 2/vision 3d/proyecto/6d pose/hinterstoisser/nubes/dataset/test_DNN/equiv_class2pose.txt'

#print(input_file)
x = input_file[0][0:3]
#print(len(input_file))

for _,coord in enumerate(input_file):
    print(coord)
    
#x = coor    
print(coord[0:3])

[ 4.95580e-02 -1.22515e-01  3.77537e-01  8.50000e+01]
[-1.82211e-01  8.04380e-02  3.46884e-01  1.45000e+02]
[2.53039e-01 3.12770e-02 3.08210e-01 2.70000e+02]
[-1.30816e-01 -2.71449e-01  2.63064e-01  4.95000e+02]
[-7.84330e-02  3.18851e-01  2.28434e-01  6.10000e+02]
[ 2.72341e-01 -2.33516e-01  1.76920e-01  6.55000e+02]
[-3.76132e-01 -2.40830e-02  1.33958e-01  9.55000e+02]
[2.33011e-01 3.00876e-01 1.23205e-01 8.40000e+02]
[ 1.57840e-02 -3.98872e-01  2.55390e-02  1.26500e+03]
[-2.74943e-01  2.88998e-01  2.97680e-02  1.11500e+03]
[ 3.96598e-01 -5.20600e-02  0.00000e+00  1.27500e+03]
[-3.24904e-01 -2.32770e-01  1.59840e-02  1.05000e+03]
[3.08100e-02 3.98812e-01 0.00000e+00 1.28500e+03]
[ 1.68218e-01 -3.62909e-01  0.00000e+00  1.31000e+03]
[-3.96598e-01  5.20600e-02  0.00000e+00  1.25000e+03]
[3.40260e-01 2.10292e-01 0.00000e+00 1.00500e+03]
[-1.18097e-01 -3.82169e-01  0.00000e+00  1.30000e+03]
[-1.18097e-01  3.82169e-01  0.00000e+00  1.29000e+03]
[ 3.96598e-01 -5.20600e-02  0.00000e+00  1.2

In [42]:
coord1 = []
for _,coord in enumerate(input_file):
    for i, coord2 in enumerate(input_file):
        distance_ = distance.euclidean(coord[0:3], coord2[0:3])
        coord1.append([distance_])
    
print(len(coord1))
coord = np.array(coord1)
coord = np.reshape(coord,(20,20))
np.save("distance_matrix",coord)

print("Ordenadas: \n",coord[2][1])

400
Ordenadas: 
 0.43972155359613657
